" Plugins
call plug#begin()

" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-commentary'
Plug 'gruvbox-community/gruvbox'
Plug 'itchyny/lightline.vim'

call plug#end()

" Keymaps
let mapleader = "\<Space>"

nnoremap <leader>b :ls<CR>:b

noremap <Leader>w :TrimWhitespace<CR>

" Behavior
set nocompatible
set autoread
set backspace=indent,eol,start
set scrolloff=8
set hidden
set mouse=a

" Tabbing
set tabstop=2
set softtabstop=2
set shiftwidth=2
set smarttab
set expandtab
set autoindent
set smartindent

" Searching
set nohlsearch
set incsearch
set ignorecase
set smartcase

" Directories
set undofile
set undodir=~/.local/state/vim/undo//
set directory=~/.local/state/vim/swap//
" set backup
set backupdir=~/.local/state/vim/backups//
set viminfofile=~/.local/state/vim/viminfo
let g:netrw_dirhistmax=0

" Appearance
set title
set background=dark
colorscheme gruvbox
let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ 'active': {
      \   'right': [['lineinfo'], ['percent'], ['filetype']],
      \ },
      \ }
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[3 q"
let &t_EI = "\<Esc>[2 q"
set termguicolors
set noshowmode
set showcmd
set ruler
" set cursorline
set noshowmatch
set number
set relativenumber
set wildmenu
set wildmode=list:longest
syntax on
highlight Normal guibg=NONE ctermbg=NONE
highlight SignColumn guibg=NONE ctermbg=NONE
highlight ExtraWhiteSpace ctermbg=red guibg=red
match ExtraWhiteSpace /\s\+$/

filetype plugin indent on

" Custom functions
function! s:trim_whitespace()
    let l:current_state = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:current_state)
endfun

command! TrimWhitespace call s:trim_whitespace()
